apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: monitoring
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: mydlqclub/dnsutils:1.3
    imagePullPolicy: IfNotPresent
    name: dnsutils
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
