apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: func121-cmf-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: func121-cmf-deploy
  targetCPUUtilizationPercentage: 50
