apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: func121-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi
  storageClassName: func121-pv
  selector:
    matchLabels:
      environment: func121

